### ISSUE TITLE
CHI_004: Quên mật khẩu với email chưa đăng ký tài khoản

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#100]
**Mô tả:**
> Kiểm tra tính năng quên mật khẩu vói email chưa đăng ký tài khoản

**Bước:**
1. Truy cập trang web mạng xã hội.
2. Chọn tính năng đăng nhập
3. Chọn chức năng quên mật khẩu
4. Nhập email chưa đăng ký
5. Nhấp nút gửi 

**Kết quả mong đợi:**

> Hiển thị thông báo email chưa đăng ký và không thực hiện gửi email

**Kết quả thực tế:**

> Hệ thống thông báo gửi yêu cầu thành công

**Mức độ ưu tiên:**

> Trung bình

**Ngày tạo:** 

> 23/11/2023

**Người tạo**

> Bùi Đặng Quốc Chí

**Kết luận:**

> Tính năng quên mật khẩu hoạt động không chính xác trong trường hợp này
[Uploading Nhom12_BugReport.docx…]()

**Comment by VoHongKhang** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">



</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_004
Test Description | Hệ   thống thông báo gửi yêu cầu thành công mặc dù tài khoản không tồn tại trên hệ   thống
Nguyên nhân | Do   chưa kiểm tra tài khoản có tồn tại trên hệ thống hay không
Cách khắc phục | Kiểm   tra tài khoản đã đăng ký trên hệ thống hay chưa
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/9468de6c-d7eb-4b33-9537-0f6804022a56)

[File Fix Bugs ](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)



</body>

</html>
