### ISSUE TITLE
CHI_005: Đăng bài viết với nội dung content dài

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#104]
**Mô tả:**
> Kiểm tra tính năng đăng bài viết trong trường hợp nội dung content dài 

**Bước:**
1. Truy cập trang web mạng xã hội.
2. Đăng nhập với tài khoản đã đăng ký.
3. Chọn tính năng đăng bài viết 
4. Nhập nội dung content vào ô bạn có suy nghĩ gì với nội dung khoảng ( 500 ký tự )
5. Nhấn button đăng bài 	

**Kết quả mong đợi:**

> Hiển thị thông báo thành công hoặc thông báo chỉ cho nhập nội dung với số ký tự nhất định

**Kết quả thực tế:**

> Hệ thông thông báo lỗi và không tắt thanh loading

**Mức độ ưu tiên:**

> Cao

**Ngày tạo:** 

> 24/11/2023

**Người tạo**

> Bùi Đặng Quốc Chí

**Kết luận:**

> Tính năng đăng bài không hoạt động chính xác trong trường hợp này
[Uploading Nhom12_BugReport.docx…]()

**Comment by VoHongKhang** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_005
Test Description | Hệ   thống thông báo lỗi và không tắt thanh loading
Nguyên nhân | Do   chưa kiểm tra số lượng kí tự
Cách khắc phục | Kiểm   tra số lượng kí tự của content
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/18fdfd70-0f3e-4b39-b8b2-a64f088cbb67)





</body>

</html>

[File Fix Bug](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)
