### ISSUE TITLE
CHI_006: Chỉnh sửa bài viết , xóa tất cả nội dung đã đăng trước đó bao gồm content và ảnh

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#108]
**Mô tả:**
> Kiểm tra tính năng chỉnh sửa bài viết với trường hợp xóa tất cả nội dung đã đăng trước đó bao gồm content và ảnh

**Bước:**
1. Truy cập trang web mạng xã hội.
2. Đăng nhập với tài khoản đã đăng ký.
3. Bấm chọn chỉnh sửa bài viết ở mục cá nhân	
4. Xóa tất cả nội dung	
5. Bám nút lưu	

**Kết quả mong đợi:**

> Không cho phép bấm nút lưu

**Kết quả thực tế:**

> Cho phép lưu và bài viết được cập nhật mà không có nội dung
**Mức độ ưu tiên:**

> Cao

**Ngày tạo:** 

> 26/11/2023

**Người tạo**

> Bùi Đặng Quốc Chí

**Kết luận:**

> Tính năng chỉnh sửa bài viết hoạt động không chính xác trong trường hợp này
[Uploading Nhom12_BugReport.docx…]()

**Comment by VoHongKhang** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_006
Test Description | Chỉnh   sửa bài viết , xóa tất cả nội dung đã đăng trước đó bao gồm content và ảnh
Nguyên nhân | Do   chưa kiểm tra nội dung sau khi chỉnh sửa
Cách khắc phục | Kiểm   tra nội dung sau khi chỉnh sửa
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/a2ffba0b-ec68-4e85-a699-cd1b4487a22f)




</body>

</html>

[File Fix Bug](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)
