### ISSUE TITLE
CHI_007: Tạo tài khoản với email đã đăng ký

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#110]
**Mô tả:**
> Kiểm tra tính năng tạo tài khoản với email đã đăng ký

**Bước:**

1. Truy cập trang web mạng xã hội.
2. Đăng nhập với tài khoản đã đăng ký.
3. Chọn vai trò sinh viên và bấm tiếp tục	
4. Nhập email='20110614@student.hcmute.edu.vn'	
5. Nhập mật khẩu password='19052002Chi03@'	
6. Nhập xác thực mật khẩu confirmpassword='19052002Chi03@'	
7. Nhấn button 'tiếp tục	
8. Nhập họ và tên : 'Bùi Đặng Quốc Chí'	
9. Nhấn chọn radio giới tính  :'Nam'	
10. Nhập số điện thoại: '0362858057	
11. Chọn tên lớp: 201101C'	
12. Nhấn button 'Xác nhận'	

**Kết quả mong đợi:**

> Hiển thị thông báo email đã tồn tại

**Kết quả thực tế:**

> Không hiển thị bất kỳ thông báo gì.

**Mức độ ưu tiên:**

> Trung bình

**Ngày tạo:** 

> 28/11/2023

**Người tạo**

> Bù Đặng Quốc Chí

**Kết luận:**

> Tính năng tạo tài khoản hoạt động không chính xác trong trường hợp này
[Nhom12_BugReport.docx](https://github.com/VoHongKhang/UteAlo_FrontEnd/files/13724896/Nhom12_BugReport.docx)

**Comment by VoHongKhang** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">



</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_006
Test Description | Không   hiển thị bất kỳ thông báo gì mặc dù tài khoản đó đã đăng ký rồi
Nguyên nhân | Do   chưa kiểm tra tài khoản đã đăng ký chưa
Cách khắc phục | Kiểm   tra tài khoản khi đăng ký
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/0c40ac1b-4206-4c05-9412-7e2f8a50a3fe)



</body>

</html>

[File Fix Bug](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)
