### ISSUE TITLE
CHI_008:  Đăng ký tài khoản với số điện thoại đã đăng ký 

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#111]
**Mô tả:**
> Kiểm tra tính năng đăng ký tài khỏan với số điện thoại đã đăng ký 

**Bước:**

1. Truy cập trang web mạng xã hội.
2. Chọn tính năng đăng ký
3. Chọn vai trò sinh viên và bấm tiếp tục	
4. Nhập email='20110614@student.hcmute.edu.vn'	
5. Nhập mật khẩu password='19052002Chi03@'	
6. Nhập xác thực mật khẩu confirmpassword='19052002Chi03@'	
7. Nhấn button 'tiếp tục	
8. Nhập họ và tên : 'Bùi Đặng Quốc Chí'	
9. Nhấn chọn radio giới tính  :'Nam'	
10. Nhập số điện thoại: '0362858057'	
11. Chọn tên lớp: 201101C'	
12. Nhấn button 'Xác nhận'	

**Kết quả mong đợi:**

> Hệ thống thông báo không đăng ký thành công

**Kết quả thực tế:**

> Không hiển thị bất kỳ thông báo gì		

**Mức độ ưu tiên:**

> Cao

**Ngày tạo:** 

> 28/11/2023

**Người tạo**

> Bùi Đặng Quốc chí

**Kết luận:**

> Tính năng đăng ký tài khoản hoạt động không chính xác trong trường hợp này
[Nhom12_BugReport.docx](https://github.com/VoHongKhang/UteAlo_FrontEnd/files/13724937/Nhom12_BugReport.docx)

**Comment by VoHongKhang** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_006
Test Description | Không   hiển thị bất kỳ thông báo gì mặc dù số điện thoại đó đã đăng ký rồi
Nguyên nhân | Do   chưa kiểm tra số điện thoại đã đăng ký chưa
Cách khắc phục | Kiểm   tra số điện thoại khi đăng ký
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/f49d9ac1-e643-462c-a763-ffe766913d4c)





</body>

</html>


[File Fix Bug](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)
