### ISSUE TITLE
ANH_039: Tạo bình luận chứ kí tự đặt biệc bên trong bài viết người khác

### ISSUE THREAD

**Issue by aducanha** [VoHongKhang/UteAlo_FrontEnd#125]
**Mô tả:**
> Tạo bình luận chứ kí tự đặt biệc bên trong bài viết người khác
**Điều kiện tiên quyết:**
> Điều hướng đến trang cá nhân của người khác '[http://localhost:3000/profile/c7803f27-29d4-42f2-ba8f-a913bd2a3e92](http://localhost:3000/update/af5ab946-1c45-4112-ad8b-5e55b6f6b33e)'
				
**Bước:**
1. Truy cập đến trang cá nhân của người khác: "http://localhost:3000/profile/c7803f27-29d4-42f2-ba8f-a913bd2a3e92"	
và tìm bài viết cần bình luận	
3. Click vào ô input nhập bình luận	
4. Nhập nội dung bình luận	
5. Nhấn vào icon [Gửi] 	
**Kết quả mong đợi:**
> Cho phép nhấn, số lượng bình luận từ 1 chuyển sang 2. Xuất hiện box bình luận đầy đủ các feature: avatar cảu mình, tên Phan Văn Đức Anh, nội dung bình luận "‘ or ‘abc‘=‘abc‘; --", thời gian đăng: 0 phút trước, số lượng thích của bình luận bằng 0				

**Kết quả thực tế:**
> Cho phép nhấn, số lượng bình luận từ 1 chuyển sang 2. Xuất hiện box bình luận đầy đủ các feature: avatar cảu mình, tên Phan Văn Đức Anh, nội dung bình luận "&amp;#39; or &amp;#39;abc&amp;#39;=&amp;#39;abc&amp;#39;; --", thời gian đăng: 0 phút trước, số lượng thích của bình luận bằng 0        

**Mức độ ưu tiên:**

> Trung bình

**Ngày tạo:** 

> 19/11/2023

**Người tạo**

> Phan Văn Đức Anh

**Kết luận:**

> Tính năng Tạo bình luận chứ kí tự đặt biệc bên trong bài viết người khác hoạt động không chính xác.

**Comment by 81quanghuy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | ANH_039
Test Description | Khi người dùng nhập khi tự đặc biệt vào bình   luận của bài post thì hệ thống không hiển thị ký tự đặc biệt đó mà hiển thị   ra các ký tự được escape
Nguyên nhân | Hệ thống nhận diện các ký tự đặc biệt có   thể ảnh hưởng đến hệ thống như bị tấn công hay hack tài khoản nên hệ thống thực   hiện kiểm tra và không cho phép nhận các kí tự đặc biệt.
Cách khắc phục | Người dùng hạn chế việc nhập các ký tự đặc   biệt vào bình luận của bài viết.
Ghi chú khác | Không


[File Fix Bugs ](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.9e6ez37jqw2m)


</body>

</html>
