### ISSUE TITLE
ANH_041: Hiển thị icon số lượng tin nhắn khi có tin nhắn mới trên thanh header

### ISSUE THREAD

**Issue by aducanha** [VoHongKhang/UteAlo_FrontEnd#127]
**Mô tả:**
> Hiển thị icon số lượng tin nhắn khi có tin nhắn mới trên thanh header
**Điều kiện tiên quyết:**
1. Tiến hành gửi tin nhắn đến tài khoản cần kiểm tra		
2. Điều hướng đến trang web UTEALO ở tài khoản cần kiểm tra "http://localhost:3000/"		

**Bước:**
1. Check icon số lượng tin nhắn tại icon: class="button-right" ở thanh header							

**Kết quả mong đợi:**
> icon tròn màu đỏ, bên trong chữ số 1 màu trắng. Icon nằm bên trên bên phải của class="button-right"					

**Kết quả thực tế:**
> Icon không xuất hiện

**Mức độ ưu tiên:**

> Trung bình

**Ngày tạo:** 

> 19/11/2023

**Người tạo**

> Phan Văn Đức Anh

**Kết luận:**

> Tính năng Hiển thị icon số lượng tin nhắn khi có tin nhắn mới trên thanh header hoạt động không chính xác.

**Comment by 81quanghuy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">




</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | ANH_041
Test Description | Khi người dùng có một tin nhắn mới thì   không hiển thị số lượng tin nhắn mới bên ô tin nhắn
Nguyên nhân | Không xử lý bên ô tin nhắn mà xử lý bên ô   thông báo
Cách khắc phục | Khi có một tin nhắn mới từ bất kỳ người   dùng hay nhóm nào thì đều hiển thị thông báo bên icon thông báo
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/94524624/94cfaa0d-d669-4e29-992d-9e6a22fb93bd)


[File Fix Bugs ](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit)


</body>

</html>
