### ISSUE TITLE
CHI_002: Đăng nhập với tài khoản không tồn tại trong hệ thống

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#86]
**Mô tả:**
> Đăng nhập với tài khoản không tồn tại trong hệ thống

**Bước:**
1. Truy cập trang web mạng xã hội.
2. Chọn tính năng nhập 
3. Nhập email và password chưa có đăng ký
4. Nhấn button đăng nhập

**Kết quả mong đợi:**

> Hệ thống thông báo tài khoản hoặc mật khẩu không đúng

**Kết quả thực tế:**

> Hệ thông bị treo và không có bất kỳ thông báo nào 

**Mức độ ưu tiên:**

> Cao

**Ngày tạo:** 

> 22/11/2023

**Người tạo**

> Bùi Đặng Quốc Chí

**Kết luận:**

> Tính năng đăng nhập hoạt động không đúng trong trường hợp này
[Nhom12_BugReport.docx](https://github.com/VoHongKhang/UteAlo_FrontEnd/files/13724678/Nhom12_BugReport.docx)

**Comment by 81quanghuy** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:offcxzccxzcxzczxczcxzczczxczcxzczxczccxzczxice:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_004
Test Description | Lỗi treo hệ thống khi nhập sai tên đăng   nhập và nhập khẩu
Nguyên nhân | Thiếu xử lý hiển thị thông báo lỗi của hệ   thống khi đăng nhập sai.
Cách khắc phục | Thêm <Toaster/> ở component cha của   trang login và thêm các toast xử lý khi đăng nhập.
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/94524624/45bfd525-8b13-436f-ac27-4eb2d1311b99)



[File FixBugs](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit)



</body>

</html>
