### ISSUE TITLE
KIET_045: Thả icon cho tin nhắn của mình trong box

### ISSUE THREAD

**Issue by 20110665** [VoHongKhang/UteAlo_FrontEnd#88]
**Mô tả:**

> Kiểm thử chức năng thả icon cho tin nhắn của mình trong box chat

**Điều kiện tiên quyết**

> Đăng nhập vào account A, truy cập box hôi thoại với acc B

**Bước:**

1. Rê chuột đến tin nhắn cần thả icon
2. Click vào icon mặt cười
3. Click vào icon cảm xúc bất kỳ cho 1 tin nhắn của account B
4. Load lại trang

**Kết quả mong đợi:**

> Icon cảm xúc vừa thả xuất hiện tại tin nhắn đó

**Kết quả thực tế:**

> Không xuất hiện cảm xúc vừa tương tác

**Mức độ ưu tiên:**

> Thấp

**Ngày tạo:**

> 18/11/2023

**Người tạo**

> Trần Văn Kiệt

**Kết luận:**

> Tính năng thả cảm xúc cho tin nhắn của mình hoạt động không chính xác

**Comment by 81quanghuy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | KIET_045
Test Description | Không hiển thị icon đã thả trong tin nhắn   của chính mình khi tải lại trang web
Nguyên nhân | Chưa xử lý sự kiện thả icon vào tin nhắn   của chính mình
Cách khắc phục | Thực hiện xử lý khi người dùng thả icon vào   tin nhắn của mình thì sẽ lưu dữ liệu lại và khi người dùng tải lại trang sẽ   hiển thị ra dữ liệu trước đó
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/94524624/a652e317-7de3-4a19-9afd-7b7b64b19a5a)


[Fiile Fix Bugs](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit)


</body>

</html>
