### ISSUE TITLE
KIET_046: Nhận icon cho tin nhắn của mình trong box từ bạn bè

### ISSUE THREAD

**Issue by 20110665** [VoHongKhang/UteAlo_FrontEnd#89]
**Mô tả:**

> Kiểm thử chức năng thả icon cho tin nhắn của bạn bè trong box

**Điều kiện tiên quyết**

> Đăng nhập vào account A, truy cập box hôi thoại với acc B
> Thả icon cảm xúc cho 1 tin nhắn từ B
> Đăng nhập vào tài khoản B

**Bước:**

1. Truy cập vào box chat với acount A
2. Kiểm tra icon vừa thả từ account A

**Kết quả mong đợi:**

> Icon cảm xúc được chọn xuất hiện góc dưới bên phải tin nhắn

**Kết quả thực tế:**

> Không xuất hiện icon cảm xúc

**Mức độ ưu tiên:**

> Thấp

**Ngày tạo:**

> 18/11/2023

**Người tạo**

> Trần Văn Kiệt

**Kết luận:**

> Tính năng nhận icon cho tin nhắn của mình trong box từ bạn bè hoạt động không chính xác

**Comment by 81quanghuy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | KIET_046
Test Description | Không hiển thị icon đã thả trong tin nhắn
Nguyên nhân | Chưa xử lý sự kiện thả icon trong nhóm   chat
Cách khắc phục | Thực hiện xử lý khi người dùng thả icon   thì tất cả thành viên kể cả người  gửi   thì đều hiển thị ra
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/94524624/1bc24923-1cac-4abe-a3a7-cc0354cdd5c3)


[File Fix Bugs](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit)


</body>

</html>
