### ISSUE TITLE
KIET_048: Hiển thị icon số lượng thông báo khi bạn bè thả icon bài viết của mình trên thanh header

### ISSUE THREAD

**Issue by 20110665** [VoHongKhang/UteAlo_FrontEnd#93]
**Mô tả:**

> Kiểm thử hiển thị icon số lượng thông báo khi bạn bè thả icon bài viết của mình trên thanh header

**Điều kiện tiên quyết**

> Đăng nhập vào account A, truy cập vào trang cá nhân của account B
> Tìm bài viết cần thả tim, thả tim cho bài viết
> Đăng nhập vào account B

**Bước:**

1. Check icon số lượng thông báo tại icon: class="MuiSvgIcon-root button-right-notifications" ở thanh header

**Kết quả mong đợi:**

> icon tròn màu đỏ, bên trong chữ số 1 màu trắng. Icon nằm bên trên bên phải của class="MuiSvgIcon-root button-right-notifications"

**Kết quả thực tế:**

> Icon không xuất hiện

**Mức độ ưu tiên:**

> Cao

**Ngày tạo:**

> 18/11/2023

**Người tạo**

> Trần Văn Kiệt

**Kết luận:**

> Tính năng hiển thị icon số lượng thông báo khi bạn bè thả icon bài viết của mình trên thanh header hoạt động không chính xác

**Comment by 81quanghuy** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/QUANGH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Ngô Diệp Quang Huy
-- | --
Ngày sửa | 27/11/2023
Test case ID | KIET_048
Test Description | Không hiển thị số lượng thông báo chưa đọc
Nguyên nhân | Không hiển thị số lượng thông báo chưa đọc   lên thanh header
Cách khắc phục | Truyền số lượng thông báo chưa đọc lên   thanh header
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/94524624/76d2ffc8-d178-4c0c-adf5-c75b4b644b71)


[File Fix Bugs](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit)


</body>

</html>
