### ISSUE TITLE
CHI_003: Tạo tài khoản với thông tin đúng yêu cầu 

### ISSUE THREAD

**Issue by 1905Chi** [VoHongKhang/UteAlo_FrontEnd#94]
**Mô tả:**
> Kiểm tra tính năng tạo tài khoản với các thông tin hợp lệ

**Bước:**

1. Truy cập trang web mạng xã hội.
2. Chọn tính năng tạo tài khoản
3. Chọn vai trò sinh viên và bấm tiếp tục	
4. Nhập email='20110614@student.hcmute.edu.vn'	
5. Nhập mật khẩu password='19052002Chi03?'	
6. Nhập xác thực mật khẩu confirmpassword='19052002Chi03?'	
7. Nhấn button 'tiếp tục	
8. Nhập họ và tên : 'Bùi Đặng Quốc Chí'	
9. Nhấn chọn radio giới tính  :'Nam'	
10. Nhập số điện thoại: '0362858057	
11. Chọn tên lớp: 201101C'	
12. Nhấn button Xác nhận	

**Kết quả mong đợi:**

> Hiển thị thông báo xác nhận tạo tài khoản thành công

**Kết quả thực tế:**

> Hệ thống thông báo lỗi ở bước nhập mật khẩu, mặc dù đã nhập đúng có ký tự đặc biệt

**Mức độ ưu tiên:**

> Cao

**Ngày tạo:** 

> 23/11/2023

**Người tạo**

> Bùi Đặng Quốc Chí

**Kết luận:**

> Tính năng tạo tài khoản hoạt động không chính xác trong trường hợp này
[Uploading Nhom12_BugReport.docx…]()

**Comment by VoHongKhang** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-4de38a15-7fff-272e-e4bc-3c53990cf82e"><div dir="ltr" style="margin-left:0pt;" align="left">
Tên LTV | Võ Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_003
Test Description | Hệ thống thông báo lỗi ở bước nhập mật khẩu, mặc dù đã nhập đúng có ký tự đặc biệt
Nguyên nhân | Do không nhập đúng yêu cầu của hệ thống
Cách khắc phục | Là phải nhập theo đúng yêu cầu của hệ thống. Những ký tự đặc biệt mà hệ thống quy định.
Ghi chú khác | Không
Hình ảnh đã fix |  

</div><br /></b>
</body>
</html>

**Comment by VoHongKhang** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VOHONG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">





</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



Tên LTV | Võ   Hồng Khang
-- | --
Ngày sửa | 27/11/2023
Test case ID | CHI_003
Test Description | Hệ   thống thông báo lỗi ở bước nhập mật khẩu, mặc dù đã nhập đúng có ký tự đặc   biệt
Nguyên nhân | Do   không nhập đúng yêu cầu của hệ thống
Cách khắc phục | Là   phải nhập theo đúng yêu cầu của hệ thống. Những ký tự đặc biệt mà hệ thống   quy định.
Ghi chú khác | Không
Hình ảnh đã fix |  ![image](https://github.com/VoHongKhang/UteAlo_FrontEnd/assets/87598819/32f79042-9532-4bdd-b4c0-403b773fa246)





</body>

</html>

 [File Fix Bug](https://docs.google.com/document/d/1uxnuknb4jMPLoTuvNtLFQOdUudHHlwjctd7umhX7fUs/edit#heading=h.ubpxsvdpvvxg)
